# CodeDeploy의 설정 파일
version: 0.0
os: linux

files:
  - source: / #인스턴스에 복사할 디렉터리 경로
    destination: /home/ubuntu/app #  인스턴스에서 파일이 복사되는 위치
    overwrite: yes # 복사할 위치에 파일이 있는 경우 대체

hooks: #배포 이후에 수행할 스크립트
  AfterInstall: #설치가 된 이후에 deploy.sh라는 스크립트를 실행
    - location: deploy.sh #hooks 에서 실행할 스크립트 위치
      timeout: 60 #스크립트 실행에 허용되는 최대 시간이며, 넘으면 배포 실패로 간주됨
      runas: ubuntu


